default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Coffee_farm_development

test:
  <<: *default
  database: Coffee_farm_test

production:
  <<: *default
  database: Coffee_farm_production
  username: Coffee_farm
  password: <%= ENV['COFFEE_FARM_DATABASE_PASSWORD'] %>
